### PR TITLE
feat(tpl): add new page full screen layout

### PR DESCRIPTION
**Pull request by fogfish**
# Description

The version v2.4.0 has broken the compatibility with v2.3.x where application had ability to define Width and Height for the page. Making it possible to stretch graph for entire browser window. This change introduces new layout to fix the issue.

---

# Type of change

- [x] Bug fix (Non-breaking change which fixes an issue)
- [x] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Would cause existing functionality to not work as expected)
- [ ] Docs
- [ ] Others

### CODE REVIEW

**Comment by Koooooo-7** [comment]
Hi @fogfish , thx for the new layout config contribution！

> The version v2.4.0 has broken the compatibility with v2.3.x where application had ability to define Width and Height for the page

But for the problem and the purpose you mentioned.
go-echarts only can define the page layout, only charts has the container size `Width and Height ` to set.

What did you mean the v2.4.0 lost compatibility? thx.

**Comment by fogfish** [comment]
@Koooooo-7  In the version 2.3.x, it was possible to make full screen layout graphs with 

```go
page := components.NewPage()
	page.Height = "100%"
	page.Width = "100%"
	page.AddCharts(
		graph,
	)
```

In the new version, width & height only impact Graph canvas.

```go
graph := charts.NewGraph()

graph.AddSeries("graph", nodes, links).
	SetGlobalOptions(
		charts.WithInitializationOpts(opts.Initialization{
			Width:  "100%",
			Height: "100%",
		}),
)
```

The issue is `div` container that wraps graphs.
https://github.com/go-echarts/go-echarts/blob/master/templates/base.tpl#L2

We need to have some api to adjust it style passing `height: 100 hv`. I think a new layout is the best to make it.

Thanks!

**Comment by Koooooo-7** [comment]
Hi @fogfish .

In v2.3+ it does have a `page.Height` configuration, but it  actually configs the `chart <div>` blocks. 
It is a wrong place of this config. so in v.2.4.0 it has been removed.

I suppose the code you posted should be the same effective since there is no a `container level configs retrieve from the Page width/height` configs either in v2.3+ or v2.4.0.

---

Introduce a new layout of page is totally fine tho.

**Review by Koooooo-7 — APPROVED** [review]

**Comment by fogfish** [comment]
@Koooooo-7 Thank you! 

Can you please tag a new version e.g. v2.4.1 so that I can reference it from upstream instead of using my fork.

**Comment by Koooooo-7** [comment]
> @Koooooo-7 Thank you!
> 
> Can you please tag a new version e.g. v2.4.1 so that I can reference it from upstream instead of using my fork.

Of cos, `v2.4.1` released now.

**Comment by fogfish** [comment]
@Koooooo-7  Thank you a lot!

btw, I am using GitHub Action to automatically tag a new version when `main` branch is updated

```yaml
      - uses: reecetech/version-increment@2023.10.2
        id: version
        with:
          scheme: semver
          increment: patch

      - name: publish
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ steps.version.outputs.v-version }}
          git push origin -u ${{ steps.version.outputs.v-version }}
```

Full example: https://github.com/kshard/vector/blob/main/.github/workflows/build.yml

**Comment by Koooooo-7** [comment]
> @Koooooo-7 Thank you a lot!
> 
> btw, I am using GitHub Action to automatically tag a new version when `main` branch is updated
> 
> ```yaml
>       - uses: reecetech/version-increment@2023.10.2
>         id: version
>         with:
>           scheme: semver
>           increment: patch
> 
>       - name: publish
>         run: |
>           git config user.name "GitHub Actions"
>           git config user.email "github-actions@users.noreply.github.com"
>           git tag ${{ steps.version.outputs.v-version }}
>           git push origin -u ${{ steps.version.outputs.v-version }}
> ```
> 
> Full example: https://github.com/kshard/vector/blob/main/.github/workflows/build.yml

Thx for the sharing.
Cos go-echarts runs on the trunk branch directly, some minor changes  I don't wanna make it release very frequently for now. weekly/monthly release or sometimes do release for users is totally fine for now.

**Pull request merged**
